name: learn-github-actions
#run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello GitHubActions Dev

  QA:
    runs-on: ubuntu-latest
    needs:
      - DEV
    steps:
      - run: echo Hello GitHubActions QA

  UAT:
    runs-on: ubuntu-latest
    needs:
      - QA
    steps:
      - run: echo Hello GitHubActions UAT


  PROD:
    runs-on: ubuntu-latest
    needs:
      - UAT
    steps:
      - run: echo Hello GitHubActions PROD